FROM openjdk:11

WORKDIR /server

COPY target/carto-server.jar carto-server.jar

ENV PORT=5000
ENV FIREBASE_ADMIN_JSON=EXAMPLE

ENV PGHOST=EXAMPLE
ENV PGPORT=EXAMPLE
ENV PGDATABASE=EXAMPLE
ENV PGUSER=EXAMPLE
ENV PGPASSWORD=EXAMPLE


ENTRYPOINT ["java", "-jar","carto-server.jar"]

EXPOSE ${PORT}