version: '3.7'

services:
  carto_server_prod:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: carto_server_prod
    env_file:
      - server-config.prod.env
    ports:
      - '5000:5000'
    networks:
      - carto_prod_net

  carto_postgres_prod:
    image: postgres
    container_name: carto_postgres_prod
    restart: always
    ports:
      - '5432:5432'
      - '127.0.0.1:8888:5432'
    env_file:
      - database.env
    volumes:
      - carto_postgres_prod:/var/lib/postgresql/data
    networks:
      - carto_prod_net

networks:
  carto_prod_net:

volumes:
  carto_postgres_prod:
    driver: local