FROM openjdk:11

WORKDIR /server

COPY target/carto-server.jar carto-server.jar

ENV PORT=5000
ENV FIREBASE_ADMIN_JSON=EXAMPLE

ENV SPRING_DATASOURCE_URL=EXAMPLE
ENV SPRING_DATASOURCE_USERNAME=EXAMPLE
ENV SPRING_DATASOURCE_PASSWORD=EXAMPLE

ENTRYPOINT ["java", "-jar","carto-server.jar"]

EXPOSE ${PORT}